backend:
  name: git-gateway
  branch: master
display_url: https://diadiaarquitectura.com
logo_url: /images/diadia-logo.svg
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: Administrador - DiaDia
    name: administrador
    delete: false
    create: false
    format: json
    files:
      - label: Proyectos
        name: proyectos
        file: content/proyectos.json
        fields:
          - label: Proyectos
            name: proyectos 
            widget: list
            fields:
              - { label: Nombre, name: nombre, required: true, widget: text }
              - { label: Descripción, name: descripcion, required: false, widget: text }
              - { label: Fecha, name: fecha, widget: date, default: '', format: 'DD MM YYYY' }
              - label: Tipología
                name: tipologia
                required: true
                widget: select
                options:
                  - { label: Vivienda, value: vivienda }
                  - { label: Educación, value: educación }
              - { label: Ubicacion, name: ubicacion, required: false, widget: text }
              - { label: Involucrados, name: involucrados, required: false, widget: text }
              - label: Galería de Fotos
                name: galería
                required: false
                widget: list
                fields:
                  - { label: Imagen, name: url, widget: image, required: false, allow_multiple: false }
                  - label: Tipo
                    name: tipo
                    required: true
                    widget: select
                    options:
                      - { label: Obra, value: obra }
                      - { label: Representación, value: representacion }
                      - { label: Maqueta, value: maqueta }
      - label: Bases
        name: bases
        file: content/bases.json
        fields:
          - { label: Imagen, name: url, widget: image, required: true, allow_multiple: false }
          - { label: Enlace Externo, name: enlace, required: false, widget: text }
          - { label: Enlace de Eescarga, name: descarga, required: false, widget: text }
