backend:
  name: git-gateway
  branch: master
display_url: https://diadiaarquitectura.com
logo_url: /images/diadia-logo-300.svg
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: Administrador - DiaDia
    name: administrador
    delete: false
    create: false
    format: json
    files:
      - label: Home
        name: home
        file: static/content/home.json
        fields:
          - { label: Título, name: titulo, required: false, widget: text }
          - { label: Texto, name: texto, required: false, widget: text }
      - label: Proyectos
        name: proyectos
        file: static/content/proyectos.json
        fields:
          - label: Proyectos
            name: proyectos 
            widget: list
            fields:
              - { label: Nombre, name: nombre, required: true, widget: text }
              - { label: Descripción, name: descripcion, required: false, widget: text }
              - { label: Fecha, name: fecha, widget: date, default: '', format: 'DD MM YYYY' }
              - label: Estado
                name: estado
                required: true
                widget: select
                default: noRealizado
                options:
                  - { label: Realizado, value: realizado }
                  - { label: No Realizado, value: noRealizado }
              - label: Tipología
                name: tipologia
                required: true
                widget: select
                options:
                  - { label: Vivienda, value: vivienda }
                  - { label: Educación, value: educación }
                  - { label: Base, value: base }
              - { label: Descargable, name: descargable, required: false, widget: text }
              - { label: Ubicacion, name: ubicacion, required: false, widget: text }
              - { label: Involucrados, name: involucrados, required: false, widget: text }
              - label: Galería de Fotos
                name: galería
                required: false
                widget: list
                fields:
                  - { label: Imagen, name: url, widget: image, required: false, allow_multiple: false }
                  - label: Tipo
                    name: tipo
                    required: true
                    widget: select
                    options:
                      - { label: Sketch, value: sketch }
                      - { label: Diagramas, value: diagramas }
                      - { label: Maquetas, value: maquetas }
                      - { label: Planimetrías, value: planimetrias }
                      - { label: Vistas 3D, value: vista3d }
                      - { label: Foto Obra, value: fotoObra }
                      - { label: Foto Uso, value: fotoUso }
                      - { label: Base, value: base }
      - label: Estudio
        name: estudio
        file: static/content/estudio.json
        fields:
          - label: Fotos
            name: galería
            required: false
            widget: list
            fields:
              - { label: Imagen, name: url, widget: image, required: false, allow_multiple: false }
            
      - label: Contacto
        name: contacto
        file: static/content/contacto.json
        fields:
          - { label: Mensaje, name: mensaje, required: false, widget: text }
          - { label: Dirección, name: direccion, required: false, widget: text }
          - { label: Email, name: email, required: false, widget: text }
          - { label: Enlace Instagram, name: enlaceInstagram, required: false, widget: text }
          - { label: Web, name: web, required: false, widget: text }
          - { label: Imagen, name: imagen, widget: image, required: false, allow_multiple: false }
